/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as DeckDeckIdStudyRouteImport } from './routes/deck.$deckId.study'

const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdStudyRoute = DeckDeckIdStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => DeckDeckIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/deck/$deckId': typeof DeckDeckIdRouteWithChildren
  '/deck/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/deck/$deckId': typeof DeckDeckIdRouteWithChildren
  '/deck/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/deck/$deckId': typeof DeckDeckIdRouteWithChildren
  '/deck/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/documents'
    | '/deck/$deckId'
    | '/deck/$deckId/study'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/documents' | '/deck/$deckId' | '/deck/$deckId/study'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/documents'
    | '/deck/$deckId'
    | '/deck/$deckId/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DocumentsRoute: typeof DocumentsRoute
  DeckDeckIdRoute: typeof DeckDeckIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/study': {
      id: '/deck/$deckId/study'
      path: '/study'
      fullPath: '/deck/$deckId/study'
      preLoaderRoute: typeof DeckDeckIdStudyRouteImport
      parentRoute: typeof DeckDeckIdRoute
    }
  }
}

interface DeckDeckIdRouteChildren {
  DeckDeckIdStudyRoute: typeof DeckDeckIdStudyRoute
}

const DeckDeckIdRouteChildren: DeckDeckIdRouteChildren = {
  DeckDeckIdStudyRoute: DeckDeckIdStudyRoute,
}

const DeckDeckIdRouteWithChildren = DeckDeckIdRoute._addFileChildren(
  DeckDeckIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DocumentsRoute: DocumentsRoute,
  DeckDeckIdRoute: DeckDeckIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
