/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ImportAnkiRouteImport } from './routes/import-anki'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as DeckDeckIdStudyRouteImport } from './routes/deck_.$deckId.study'
import { Route as DeckDeckIdQuizRouteImport } from './routes/deck_.$deckId.quiz'
import { Route as ApiCloudinarySignatureRouteImport } from './routes/api.cloudinary.signature'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportAnkiRoute = ImportAnkiRouteImport.update({
  id: '/import-anki',
  path: '/import-anki',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdStudyRoute = DeckDeckIdStudyRouteImport.update({
  id: '/deck_/$deckId/study',
  path: '/deck/$deckId/study',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdQuizRoute = DeckDeckIdQuizRouteImport.update({
  id: '/deck_/$deckId/quiz',
  path: '/deck/$deckId/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudinarySignatureRoute = ApiCloudinarySignatureRouteImport.update({
  id: '/api/cloudinary/signature',
  path: '/api/cloudinary/signature',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import-anki': typeof ImportAnkiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/api/cloudinary/signature': typeof ApiCloudinarySignatureRoute
  '/deck/$deckId/quiz': typeof DeckDeckIdQuizRoute
  '/deck/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import-anki': typeof ImportAnkiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/api/cloudinary/signature': typeof ApiCloudinarySignatureRoute
  '/deck/$deckId/quiz': typeof DeckDeckIdQuizRoute
  '/deck/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import-anki': typeof ImportAnkiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/api/cloudinary/signature': typeof ApiCloudinarySignatureRoute
  '/deck_/$deckId/quiz': typeof DeckDeckIdQuizRoute
  '/deck_/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/documents'
    | '/import-anki'
    | '/reset-password'
    | '/deck/$deckId'
    | '/api/cloudinary/signature'
    | '/deck/$deckId/quiz'
    | '/deck/$deckId/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/documents'
    | '/import-anki'
    | '/reset-password'
    | '/deck/$deckId'
    | '/api/cloudinary/signature'
    | '/deck/$deckId/quiz'
    | '/deck/$deckId/study'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/documents'
    | '/import-anki'
    | '/reset-password'
    | '/deck/$deckId'
    | '/api/cloudinary/signature'
    | '/deck_/$deckId/quiz'
    | '/deck_/$deckId/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DocumentsRoute: typeof DocumentsRoute
  ImportAnkiRoute: typeof ImportAnkiRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  ApiCloudinarySignatureRoute: typeof ApiCloudinarySignatureRoute
  DeckDeckIdQuizRoute: typeof DeckDeckIdQuizRoute
  DeckDeckIdStudyRoute: typeof DeckDeckIdStudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-anki': {
      id: '/import-anki'
      path: '/import-anki'
      fullPath: '/import-anki'
      preLoaderRoute: typeof ImportAnkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck_/$deckId/study': {
      id: '/deck_/$deckId/study'
      path: '/deck/$deckId/study'
      fullPath: '/deck/$deckId/study'
      preLoaderRoute: typeof DeckDeckIdStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck_/$deckId/quiz': {
      id: '/deck_/$deckId/quiz'
      path: '/deck/$deckId/quiz'
      fullPath: '/deck/$deckId/quiz'
      preLoaderRoute: typeof DeckDeckIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudinary/signature': {
      id: '/api/cloudinary/signature'
      path: '/api/cloudinary/signature'
      fullPath: '/api/cloudinary/signature'
      preLoaderRoute: typeof ApiCloudinarySignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DocumentsRoute: DocumentsRoute,
  ImportAnkiRoute: ImportAnkiRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  ApiCloudinarySignatureRoute: ApiCloudinarySignatureRoute,
  DeckDeckIdQuizRoute: DeckDeckIdQuizRoute,
  DeckDeckIdStudyRoute: DeckDeckIdStudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
