/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ImportAnkiRouteImport } from './routes/import-anki'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as DeckDeckIdStudyRouteImport } from './routes/deck_.$deckId.study'
import { Route as DeckDeckIdSmcqRouteImport } from './routes/deck_.$deckId.smcq'
import { Route as DeckDeckIdQuizRouteImport } from './routes/deck_.$deckId.quiz'
import { Route as DeckDeckIdPairmcqRouteImport } from './routes/deck_.$deckId.pairmcq'
import { Route as ApiCloudinarySignatureRouteImport } from './routes/api.cloudinary.signature'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportAnkiRoute = ImportAnkiRouteImport.update({
  id: '/import-anki',
  path: '/import-anki',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeckDeckIdStudyRoute = DeckDeckIdStudyRouteImport.update({
  id: '/deck_/$deckId/study',
  path: '/deck/$deckId/study',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdSmcqRoute = DeckDeckIdSmcqRouteImport.update({
  id: '/deck_/$deckId/smcq',
  path: '/deck/$deckId/smcq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdQuizRoute = DeckDeckIdQuizRouteImport.update({
  id: '/deck_/$deckId/quiz',
  path: '/deck/$deckId/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdPairmcqRoute = DeckDeckIdPairmcqRouteImport.update({
  id: '/deck_/$deckId/pairmcq',
  path: '/deck/$deckId/pairmcq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudinarySignatureRoute = ApiCloudinarySignatureRouteImport.update({
  id: '/api/cloudinary/signature',
  path: '/api/cloudinary/signature',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import-anki': typeof ImportAnkiRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/cloudinary/signature': typeof ApiCloudinarySignatureRoute
  '/deck/$deckId/pairmcq': typeof DeckDeckIdPairmcqRoute
  '/deck/$deckId/quiz': typeof DeckDeckIdQuizRoute
  '/deck/$deckId/smcq': typeof DeckDeckIdSmcqRoute
  '/deck/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import-anki': typeof ImportAnkiRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/cloudinary/signature': typeof ApiCloudinarySignatureRoute
  '/deck/$deckId/pairmcq': typeof DeckDeckIdPairmcqRoute
  '/deck/$deckId/quiz': typeof DeckDeckIdQuizRoute
  '/deck/$deckId/smcq': typeof DeckDeckIdSmcqRoute
  '/deck/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import-anki': typeof ImportAnkiRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/cloudinary/signature': typeof ApiCloudinarySignatureRoute
  '/deck_/$deckId/pairmcq': typeof DeckDeckIdPairmcqRoute
  '/deck_/$deckId/quiz': typeof DeckDeckIdQuizRoute
  '/deck_/$deckId/smcq': typeof DeckDeckIdSmcqRoute
  '/deck_/$deckId/study': typeof DeckDeckIdStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/documents'
    | '/import-anki'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/deck/$deckId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/cloudinary/signature'
    | '/deck/$deckId/pairmcq'
    | '/deck/$deckId/quiz'
    | '/deck/$deckId/smcq'
    | '/deck/$deckId/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/documents'
    | '/import-anki'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/deck/$deckId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/cloudinary/signature'
    | '/deck/$deckId/pairmcq'
    | '/deck/$deckId/quiz'
    | '/deck/$deckId/smcq'
    | '/deck/$deckId/study'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/documents'
    | '/import-anki'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/deck/$deckId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/cloudinary/signature'
    | '/deck_/$deckId/pairmcq'
    | '/deck_/$deckId/quiz'
    | '/deck_/$deckId/smcq'
    | '/deck_/$deckId/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DocumentsRoute: typeof DocumentsRoute
  ImportAnkiRoute: typeof ImportAnkiRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiCloudinarySignatureRoute: typeof ApiCloudinarySignatureRoute
  DeckDeckIdPairmcqRoute: typeof DeckDeckIdPairmcqRoute
  DeckDeckIdQuizRoute: typeof DeckDeckIdQuizRoute
  DeckDeckIdSmcqRoute: typeof DeckDeckIdSmcqRoute
  DeckDeckIdStudyRoute: typeof DeckDeckIdStudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-anki': {
      id: '/import-anki'
      path: '/import-anki'
      fullPath: '/import-anki'
      preLoaderRoute: typeof ImportAnkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck_/$deckId/study': {
      id: '/deck_/$deckId/study'
      path: '/deck/$deckId/study'
      fullPath: '/deck/$deckId/study'
      preLoaderRoute: typeof DeckDeckIdStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck_/$deckId/smcq': {
      id: '/deck_/$deckId/smcq'
      path: '/deck/$deckId/smcq'
      fullPath: '/deck/$deckId/smcq'
      preLoaderRoute: typeof DeckDeckIdSmcqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck_/$deckId/quiz': {
      id: '/deck_/$deckId/quiz'
      path: '/deck/$deckId/quiz'
      fullPath: '/deck/$deckId/quiz'
      preLoaderRoute: typeof DeckDeckIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck_/$deckId/pairmcq': {
      id: '/deck_/$deckId/pairmcq'
      path: '/deck/$deckId/pairmcq'
      fullPath: '/deck/$deckId/pairmcq'
      preLoaderRoute: typeof DeckDeckIdPairmcqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudinary/signature': {
      id: '/api/cloudinary/signature'
      path: '/api/cloudinary/signature'
      fullPath: '/api/cloudinary/signature'
      preLoaderRoute: typeof ApiCloudinarySignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DocumentsRoute: DocumentsRoute,
  ImportAnkiRoute: ImportAnkiRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiCloudinarySignatureRoute: ApiCloudinarySignatureRoute,
  DeckDeckIdPairmcqRoute: DeckDeckIdPairmcqRoute,
  DeckDeckIdQuizRoute: DeckDeckIdQuizRoute,
  DeckDeckIdSmcqRoute: DeckDeckIdSmcqRoute,
  DeckDeckIdStudyRoute: DeckDeckIdStudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
